# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'boardSsNtDI.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QGraphicsView, QGridLayout,
    QHBoxLayout, QMainWindow, QMenu, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSpacerItem,
    QStatusBar, QTabWidget, QToolBar, QWidget)
import Icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1060, 702)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(u"")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionTemplates = QAction(MainWindow)
        self.actionTemplates.setObjectName(u"actionTemplates")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionDocument = QAction(MainWindow)
        self.actionDocument.setObjectName(u"actionDocument")
        self.actionHost = QAction(MainWindow)
        self.actionHost.setObjectName(u"actionHost")
        self.actionJoin = QAction(MainWindow)
        self.actionJoin.setObjectName(u"actionJoin")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        self.tb_actionCursor = QAction(MainWindow)
        self.tb_actionCursor.setObjectName(u"tb_actionCursor")
        self.tb_actionCursor.setCheckable(True)
        icon = QIcon()
        icon.addFile(u":/Tools/cursor.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionCursor.setIcon(icon)
        self.tb_actionPen = QAction(MainWindow)
        self.tb_actionPen.setObjectName(u"tb_actionPen")
        self.tb_actionPen.setCheckable(True)
        icon1 = QIcon()
        icon1.addFile(u":/Tools/pen.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionPen.setIcon(icon1)
        self.tb_actionHighlighter = QAction(MainWindow)
        self.tb_actionHighlighter.setObjectName(u"tb_actionHighlighter")
        self.tb_actionHighlighter.setCheckable(True)
        icon2 = QIcon()
        icon2.addFile(u":/Tools/highlighter.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionHighlighter.setIcon(icon2)
        self.tb_actionEraser = QAction(MainWindow)
        self.tb_actionEraser.setObjectName(u"tb_actionEraser")
        self.tb_actionEraser.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u":/Tools/eraser.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionEraser.setIcon(icon3)
        self.tb_actionLine = QAction(MainWindow)
        self.tb_actionLine.setObjectName(u"tb_actionLine")
        self.tb_actionLine.setCheckable(True)
        icon4 = QIcon()
        icon4.addFile(u":/Tools/line.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionLine.setIcon(icon4)
        self.tb_actionShapes = QAction(MainWindow)
        self.tb_actionShapes.setObjectName(u"tb_actionShapes")
        self.tb_actionShapes.setCheckable(True)
        icon5 = QIcon()
        icon5.addFile(u":/Tools/shapes.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionShapes.setIcon(icon5)
        self.tb_actionImages = QAction(MainWindow)
        self.tb_actionImages.setObjectName(u"tb_actionImages")
        self.tb_actionImages.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/Tools/image.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionImages.setIcon(icon6)
        self.tb_actionVideos = QAction(MainWindow)
        self.tb_actionVideos.setObjectName(u"tb_actionVideos")
        self.tb_actionVideos.setCheckable(True)
        icon7 = QIcon()
        icon7.addFile(u":/Tools/video.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionVideos.setIcon(icon7)
        self.tb_actionUndo = QAction(MainWindow)
        self.tb_actionUndo.setObjectName(u"tb_actionUndo")
        icon8 = QIcon()
        icon8.addFile(u":/Tools/undo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionUndo.setIcon(icon8)
        self.tb_actionRedo = QAction(MainWindow)
        self.tb_actionRedo.setObjectName(u"tb_actionRedo")
        icon9 = QIcon()
        icon9.addFile(u":/Tools/redo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionRedo.setIcon(icon9)
        self.tb_actionSelection = QAction(MainWindow)
        self.tb_actionSelection.setObjectName(u"tb_actionSelection")
        self.tb_actionSelection.setCheckable(True)
        icon10 = QIcon()
        icon10.addFile(u":/Tools/selection.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionSelection.setIcon(icon10)
        self.tb_actionText = QAction(MainWindow)
        self.tb_actionText.setObjectName(u"tb_actionText")
        self.tb_actionText.setCheckable(True)
        icon11 = QIcon()
        icon11.addFile(u":/Tools/text.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tb_actionText.setIcon(icon11)
        self.actionChat = QAction(MainWindow)
        self.actionChat.setObjectName(u"actionChat")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(-1, 5, 0, 0)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(880, 0))
        self.tabWidget.setMaximumSize(QSize(850, 16777215))
        font = QFont()
        font.setFamilies([u"Yu Gothic UI"])
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"QTabBar::close-button {\n"
"    image: url(:Tools/close.png);\n"
"	margin-left: 7px;\n"
"	margin-top: 7px;\n"
"	margin-bottom: 5px\n"
"}\n"
"QTabWidget::pane{\n"
"	border: 2px solid;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QTabBar{\n"
"	border-top-right-radius: 10px;\n"
"	border-top-left-radius: 10px;\n"
"	border: 2px solid;\n"
"}\n"
"")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)

        # self.notebook = QWidget()
        # self.notebook.setObjectName(u"notebook")
        # self.notebook.setMinimumSize(QSize(850, 0))
        # self.notebook.setStyleSheet(u"")
        # self.gridLayout = QGridLayout(self.notebook)
        # self.gridLayout.setObjectName(u"gridLayout")
        # self.gridLayout.setContentsMargins(0, 0, 0, 0)
        # self.scrollArea_2 = QScrollArea(self.notebook)
        # self.scrollArea_2.setObjectName(u"scrollArea_2")
        # self.scrollArea_2.setMinimumSize(QSize(0, 0))
        # self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        # self.scrollArea_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        # self.scrollArea_2.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        # self.scrollArea_2.setWidgetResizable(True)
        # self.scrollAreaWidgetContents_3 = QWidget()
        # self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        # self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 850, 1100))
        # self.scrollAreaWidgetContents_3.setMinimumSize(QSize(850, 1100))
        # self.scrollAreaWidgetContents_3.setMaximumSize(QSize(850, 1100))
        # self.horizontalLayout_2 = QHBoxLayout(self.scrollAreaWidgetContents_3)
        # self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        # self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        # self.gv_Canvas = QGraphicsView(self.scrollAreaWidgetContents_3)
        # self.gv_Canvas.setObjectName(u"gv_Canvas")
        # sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        # sizePolicy1.setHorizontalStretch(0)
        # sizePolicy1.setVerticalStretch(0)
        # sizePolicy1.setHeightForWidth(self.gv_Canvas.sizePolicy().hasHeightForWidth())
        # self.gv_Canvas.setSizePolicy(sizePolicy1)
        # self.gv_Canvas.setMinimumSize(QSize(850, 1100))
        # self.gv_Canvas.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.ArrowCursor))
        # self.gv_Canvas.setStyleSheet(u"border:0px;")
        # self.gv_Canvas.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        # self.gv_Canvas.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        # self.gv_Canvas.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)

        # self.horizontalLayout_2.addWidget(self.gv_Canvas)
        #
        # self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        #
        # self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)

        # self.tabWidget.addTab(self.notebook, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.pb_AddPage = QPushButton(self.centralwidget)
        self.pb_AddPage.setObjectName(u"pb_AddPage")
        icon12 = QIcon()
        icon12.addFile(u":/Tools/plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pb_AddPage.setIcon(icon12)
        self.pb_AddPage.setFlat(True)

        self.horizontalLayout.addWidget(self.pb_AddPage)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.horizontalLayout.setStretch(0, 94)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1060, 33))
        font1 = QFont()
        font1.setBold(True)
        self.menubar.setFont(font1)
        self.menubar.setStyleSheet(u"background-color: rgb(141, 200, 216);\n"
"color: rgb(255, 255, 255);")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuCollab = QMenu(self.menubar)
        self.menuCollab.setObjectName(u"menuCollab")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tb_toolbar_main_window = QToolBar(MainWindow)
        self.tb_toolbar_main_window.setObjectName(u"tb_toolbar_main_window")
        self.tb_toolbar_main_window.setEnabled(True)
        self.tb_toolbar_main_window.setMouseTracking(True)
        self.tb_toolbar_main_window.setTabletTracking(True)
        self.tb_toolbar_main_window.setAutoFillBackground(True)
        self.tb_toolbar_main_window.setIconSize(QSize(30, 30))
        MainWindow.addToolBar(Qt.ToolBarArea.LeftToolBarArea, self.tb_toolbar_main_window)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuCollab.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionClose)
        self.menuOptions.addAction(self.actionTemplates)
        self.menuOptions.addAction(self.actionCut)
        self.menuOptions.addAction(self.actionCopy)
        self.menuOptions.addAction(self.actionPaste)
        self.menuOptions.addAction(self.actionSelect_All)
        self.menuOptions.addAction(self.actionClear)
        self.menuCollab.addAction(self.actionHost)
        self.menuCollab.addAction(self.actionJoin)
        self.menuCollab.addAction(self.actionChat)
        self.menuHelp.addAction(self.actionDocument)
        self.tb_toolbar_main_window.addAction(self.tb_actionCursor)
        self.tb_toolbar_main_window.addAction(self.tb_actionPen)
        self.tb_toolbar_main_window.addAction(self.tb_actionEraser)
        self.tb_toolbar_main_window.addAction(self.tb_actionHighlighter)
        self.tb_toolbar_main_window.addAction(self.tb_actionLine)
        self.tb_toolbar_main_window.addAction(self.tb_actionSelection)
        self.tb_toolbar_main_window.addAction(self.tb_actionText)
        self.tb_toolbar_main_window.addAction(self.tb_actionShapes)
        self.tb_toolbar_main_window.addAction(self.tb_actionImages)
        self.tb_toolbar_main_window.addAction(self.tb_actionVideos)
        self.tb_toolbar_main_window.addSeparator()
        self.tb_toolbar_main_window.addAction(self.tb_actionUndo)
        self.tb_toolbar_main_window.addAction(self.tb_actionRedo)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionTemplates.setText(QCoreApplication.translate("MainWindow", u"Templates", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionDocument.setText(QCoreApplication.translate("MainWindow", u"Document", None))
        self.actionHost.setText(QCoreApplication.translate("MainWindow", u"Host", None))
        self.actionJoin.setText(QCoreApplication.translate("MainWindow", u"Join", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionSelect_All.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.tb_actionCursor.setText(QCoreApplication.translate("MainWindow", u"Cursor", None))
        self.tb_actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
        self.tb_actionHighlighter.setText(QCoreApplication.translate("MainWindow", u"Highlighter", None))
        self.tb_actionEraser.setText(QCoreApplication.translate("MainWindow", u"Eraser", None))
        self.tb_actionLine.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        self.tb_actionShapes.setText(QCoreApplication.translate("MainWindow", u"Shapes", None))
        self.tb_actionImages.setText(QCoreApplication.translate("MainWindow", u"Images", None))
        self.tb_actionVideos.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.tb_actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.tb_actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.tb_actionSelection.setText(QCoreApplication.translate("MainWindow", u"Selection", None))
        self.tb_actionText.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.actionChat.setText(QCoreApplication.translate("MainWindow", u"Chat", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.notebook), QCoreApplication.translate("MainWindow", u"Notebook 1", None))
        self.pb_AddPage.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuCollab.setTitle(QCoreApplication.translate("MainWindow", u"Collab", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.tb_toolbar_main_window.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi