# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'boardcvKVAQ.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QGraphicsView, QGridLayout,
    QHBoxLayout, QMainWindow, QMenu, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSpacerItem,
    QStatusBar, QTabWidget, QToolBar, QWidget)
import Icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1177, 656)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(u"")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionTemplates = QAction(MainWindow)
        self.actionTemplates.setObjectName(u"actionTemplates")
        self.actionShare = QAction(MainWindow)
        self.actionShare.setObjectName(u"actionShare")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionDocument = QAction(MainWindow)
        self.actionDocument.setObjectName(u"actionDocument")
        self.actionHost = QAction(MainWindow)
        self.actionHost.setObjectName(u"actionHost")
        self.actionJoin = QAction(MainWindow)
        self.actionJoin.setObjectName(u"actionJoin")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionCursor = QAction(MainWindow)
        self.actionCursor.setObjectName(u"actionCursor")
        self.actionCursor.setCheckable(True)
        icon = QIcon()
        icon.addFile(u":/Tools/cursor.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCursor.setIcon(icon)
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        self.actionPen.setCheckable(True)
        icon1 = QIcon()
        icon1.addFile(u":/Tools/pen.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPen.setIcon(icon1)
        self.actionHighlighter = QAction(MainWindow)
        self.actionHighlighter.setObjectName(u"actionHighlighter")
        self.actionHighlighter.setCheckable(True)
        icon2 = QIcon()
        icon2.addFile(u":/Tools/highlighter.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHighlighter.setIcon(icon2)
        self.actionEraser = QAction(MainWindow)
        self.actionEraser.setObjectName(u"actionEraser")
        self.actionEraser.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u":/Tools/eraser.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionEraser.setIcon(icon3)
        self.actionLine = QAction(MainWindow)
        self.actionLine.setObjectName(u"actionLine")
        self.actionLine.setCheckable(True)
        icon4 = QIcon()
        icon4.addFile(u":/Tools/line.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLine.setIcon(icon4)
        self.actionShapes = QAction(MainWindow)
        self.actionShapes.setObjectName(u"actionShapes")
        self.actionShapes.setCheckable(True)
        icon5 = QIcon()
        icon5.addFile(u":/Tools/shapes.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionShapes.setIcon(icon5)
        self.actionImages = QAction(MainWindow)
        self.actionImages.setObjectName(u"actionImages")
        self.actionImages.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/Tools/image.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImages.setIcon(icon6)
        self.actionVideos = QAction(MainWindow)
        self.actionVideos.setObjectName(u"actionVideos")
        self.actionVideos.setCheckable(True)
        icon7 = QIcon()
        icon7.addFile(u":/Tools/video.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionVideos.setIcon(icon7)
        self.actionUndo_2 = QAction(MainWindow)
        self.actionUndo_2.setObjectName(u"actionUndo_2")
        icon8 = QIcon()
        icon8.addFile(u":/Tools/undo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionUndo_2.setIcon(icon8)
        self.actionRedo_2 = QAction(MainWindow)
        self.actionRedo_2.setObjectName(u"actionRedo_2")
        icon9 = QIcon()
        icon9.addFile(u":/Tools/redo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRedo_2.setIcon(icon9)
        self.actionSelection = QAction(MainWindow)
        self.actionSelection.setObjectName(u"actionSelection")
        self.actionSelection.setCheckable(True)
        icon10 = QIcon()
        icon10.addFile(u":/Tools/selection.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSelection.setIcon(icon10)
        self.actionText = QAction(MainWindow)
        self.actionText.setObjectName(u"actionText")
        self.actionText.setCheckable(True)
        icon11 = QIcon()
        icon11.addFile(u":/Tools/text.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionText.setIcon(icon11)
        self.actionChat = QAction(MainWindow)
        self.actionChat.setObjectName(u"actionChat")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(880, 0))
        self.tabWidget.setMaximumSize(QSize(850, 16777215))
        font = QFont()
        font.setFamilies([u"Yu Gothic UI"])
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"QTabBar::close-button {\n"
"    image: url(:Tools/close.png);\n"
"	margin-left: 7px;\n"
"	margin-top: 7px;\n"
"	margin-bottom: 5px\n"
"}\n"
"QTabWidget::pane{\n"
"	border: 2px solid;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QTabBar{\n"
"	border: 2px solid;\n"
"	border-top-right-radius: 10px;\n"
"	border-top-left-radius: 10px;\n"
"}\n"
"")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.notebook_1 = QWidget()
        self.notebook_1.setObjectName(u"notebook_1")
        self.notebook_1.setMinimumSize(QSize(850, 0))
        self.notebook_1.setStyleSheet(u"QTabBar{\n"
"	border: 2px solid ;\n"
"}")
        self.gridLayout = QGridLayout(self.notebook_1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_2 = QScrollArea(self.notebook_1)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setMinimumSize(QSize(0, 0))
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_2.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 850, 1100))
        self.scrollAreaWidgetContents_3.setMinimumSize(QSize(850, 1100))
        self.scrollAreaWidgetContents_3.setMaximumSize(QSize(850, 1100))
        self.horizontalLayout_2 = QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gv_Canvas = QGraphicsView(self.scrollAreaWidgetContents_3)
        self.gv_Canvas.setObjectName(u"gv_Canvas")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.gv_Canvas.sizePolicy().hasHeightForWidth())
        self.gv_Canvas.setSizePolicy(sizePolicy1)
        self.gv_Canvas.setMinimumSize(QSize(850, 1100))
        self.gv_Canvas.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.ArrowCursor))
        self.gv_Canvas.setStyleSheet(u"border:0px;")
        self.gv_Canvas.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.gv_Canvas.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.gv_Canvas.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)

        self.horizontalLayout_2.addWidget(self.gv_Canvas)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)

        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)

        self.tabWidget.addTab(self.notebook_1, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        self.pb_AddPage = QPushButton(self.centralwidget)
        self.pb_AddPage.setObjectName(u"pb_AddPage")
        icon12 = QIcon()
        icon12.addFile(u":/Tools/plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pb_AddPage.setIcon(icon12)
        self.pb_AddPage.setFlat(True)

        self.horizontalLayout.addWidget(self.pb_AddPage)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.horizontalLayout.setStretch(0, 100)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1177, 33))
        font1 = QFont()
        font1.setFamilies([u"Yu Gothic UI"])
        font1.setBold(True)
        font1.setItalic(False)
        self.menubar.setFont(font1)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuCollab = QMenu(self.menubar)
        self.menuCollab.setObjectName(u"menuCollab")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.LeftToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuCollab.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionClose)
        self.menuOptions.addAction(self.actionTemplates)
        self.menuOptions.addAction(self.actionCut)
        self.menuOptions.addAction(self.actionCopy)
        self.menuOptions.addAction(self.actionPaste)
        self.menuOptions.addAction(self.actionSelect_All)
        self.menuOptions.addAction(self.actionDelete)
        self.menuCollab.addAction(self.actionHost)
        self.menuCollab.addAction(self.actionJoin)
        self.menuCollab.addAction(self.actionChat)
        self.menuHelp.addAction(self.actionDocument)
        self.toolBar.addAction(self.actionCursor)
        self.toolBar.addAction(self.actionPen)
        self.toolBar.addAction(self.actionHighlighter)
        self.toolBar.addAction(self.actionEraser)
        self.toolBar.addAction(self.actionLine)
        self.toolBar.addAction(self.actionSelection)
        self.toolBar.addAction(self.actionText)
        self.toolBar.addAction(self.actionShapes)
        self.toolBar.addAction(self.actionImages)
        self.toolBar.addAction(self.actionVideos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo_2)
        self.toolBar.addAction(self.actionRedo_2)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionTemplates.setText(QCoreApplication.translate("MainWindow", u"Templates", None))
        self.actionShare.setText(QCoreApplication.translate("MainWindow", u"Share", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionDocument.setText(QCoreApplication.translate("MainWindow", u"Document", None))
        self.actionHost.setText(QCoreApplication.translate("MainWindow", u"Host", None))
        self.actionJoin.setText(QCoreApplication.translate("MainWindow", u"Join", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionSelect_All.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionCursor.setText(QCoreApplication.translate("MainWindow", u"Cursor", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
        self.actionHighlighter.setText(QCoreApplication.translate("MainWindow", u"Highlighter", None))
        self.actionEraser.setText(QCoreApplication.translate("MainWindow", u"Eraser", None))
        self.actionLine.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        self.actionShapes.setText(QCoreApplication.translate("MainWindow", u"Shapes", None))
        self.actionImages.setText(QCoreApplication.translate("MainWindow", u"Images", None))
        self.actionVideos.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.actionUndo_2.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo_2.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionSelection.setText(QCoreApplication.translate("MainWindow", u"Selection", None))
        self.actionText.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.actionChat.setText(QCoreApplication.translate("MainWindow", u"Chat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notebook_1), QCoreApplication.translate("MainWindow", u"Notebook 1", None))
        self.pb_AddPage.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuCollab.setTitle(QCoreApplication.translate("MainWindow", u"Collab", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

